services:
  postgres:
    image: postgres:15
    container_name: proksi_postgres
    environment:
      POSTGRES_DB: proksi_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d proksi_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: 